INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('BOB', 250.00);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('JANE', 1250.00);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('WALL', 250.00);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('PETER', 551.00);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('OSCAR', 2005.00);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('KENNEDY', 950.00);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('NEWTON', 232.00);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES('OBAMA', 123.00);